### ISSUE TITLE
Deep supervision

### ISSUE THREAD

**Issue by ikboljon** [MIC-DKFZ/MedNeXt#1]
Hi.

The paper is a great read. I have a question regarding deep supervision, which is not explained in the paper, but you have that in the main figure. Did you use deep supervision for all the other models that are used for comparison? If not, how can we make sure that the performance improvement is not caused by deep supervision (which theoretically is the case)?

Thank you for the response.

Regards,
Ikboljon Sobirov

**Comment by saikat-roy** [comment]
Hey Ikboljon,

Thanks for the question. Our main competitor during development was nnUNet - both nnUNet and MedNeXt uses deep supervision while allows for an equivalent comparison between these 2 nets.

Since a majority of the other baselines (4 out of the 6) didn't use deep supervision in their original publications - we decided to keep things uniform and not use deep supervision in all 6 model. However, you are right to point this out as this was raised in the MICCAI reviews as well - we hope to follow-up on this work and test deep-supervision to the 2 out of 6 baselines that used them in the original publication in later work. 

Regards,
Saikat

**Comment by ikboljon** [comment]
Dear Saikat,

Thank you very much for the clarification.

Regards,
Ikboljon Sobirov

**Comment by Z-Hd** [comment]
How to shutdown deep supervision? I met a error as follow：
Traceback (most recent call last):
  File "/root/miniconda3/bin/mednextv1_train", line 33, in <module>
    sys.exit(load_entry_point('mednextv1', 'console_scripts', 'mednextv1_train')())
  File "/root/autodl-tmp/mednext/nnunet_mednext/run/run_training.py", line 188, in main
    trainer.run_training()
  File "/root/autodl-tmp/mednext/nnunet_mednext/training/network_training/nnUNetTrainerV2.py", line 440, in run_training
    ret = super().run_training()
  File "/root/autodl-tmp/mednext/nnunet_mednext/training/network_training/nnUNetTrainer.py", line 318, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/root/autodl-tmp/mednext/nnunet_mednext/training/network_training/network_trainer.py", line 456, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/root/autodl-tmp/mednext/nnunet_mednext/training/network_training/nnUNetTrainerV2.py", line 249, in run_iteration
    l = self.loss(output, target)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/mednext/nnunet_mednext/training/loss_functions/deep_supervision.py", line 32, in forward
    assert isinstance(x, (tuple, list)), "x must be either tuple or list"
AssertionError: x must be either tuple or list

Can I simply replace this loss function? Thanks！
