### ISSUE TITLE
I encountered a problem in the preprocessing stage, how should I solve it?

### ISSUE THREAD

**Issue by Yuanyangkai** [MIC-DKFZ/MedNeXt#18]
(MeNeXt) PS E:\PythonProject\MedNeXt> mednextv1_plan_and_preprocess -t 521 -pl3d ExperimentPlanner3D_v21_customTargetSpacing_1x1x1
E:\PythonProject\MedNeXt\mednext\DATASET\nnUNet_raw_data_base\nnUNet_raw_data\Task521_Lung\imagesTr\CTA_007
E:\PythonProject\MedNeXt\mednext\DATASET\nnUNet_raw_data_base\nnUNet_raw_data\Task521_Lung\imagesTr\CTA_001
E:\PythonProject\MedNeXt\mednext\DATASET\nnUNet_raw_data_base\nnUNet_raw_data\Task521_Lung\imagesTr\CTA_002
E:\PythonProject\MedNeXt\mednext\DATASET\nnUNet_raw_data_base\nnUNet_raw_data\Task521_Lung\imagesTr\CTA_006
E:\PythonProject\MedNeXt\mednext\DATASET\nnUNet_raw_data_base\nnUNet_raw_data\Task521_Lung\imagesTr\CTA_005
E:\PythonProject\MedNeXt\mednext\DATASET\nnUNet_raw_data_base\nnUNet_raw_data\Task521_Lung\imagesTr\CTA_004
E:\PythonProject\MedNeXt\mednext\DATASET\nnUNet_raw_data_base\nnUNet_raw_data\Task521_Lung\imagesTr\CTA_003

 Task521_Lung
number of threads:  (8, 8)

D:\Anaconda3\envs\MeNeXT\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
D:\Anaconda3\envs\MeNeXT\lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
not using nonzero mask for normalization
Are we using the nonzero mask for normalization? OrderedDict([(0, False)])
Traceback (most recent call last):
  File "\\?\D:\Anaconda3\envs\MeNeXt\Scripts\mednextv1_plan_and_preprocess-script.py", line 33, in <module>
    sys.exit(load_entry_point('mednextv1', 'console_scripts', 'mednextv1_plan_and_preprocess')())
  File "e:\pythonproject\mednext\mednext\nnunet_mednext\experiment_planning\nnUNet_plan_and_preprocess.py", line 159, in main
    exp_planner.plan_experiment()
  File "e:\pythonproject\mednext\mednext\nnunet_mednext\experiment_planning\experiment_planner_baseline_3DUNet.py", line 266, in plan_experiment
    median_shape = np.median(np.vstack(new_shapes), 0)
  File "D:\Anaconda3\envs\MeNeXT\lib\site-packages\numpy\core\shape_base.py", line 289, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
ValueError: need at least one array to concatenate

**Comment by saikat-roy** [comment]
Hey @Yuanyangkai, have you managed to solve this issue?

**Comment by Yuanyangkai** [comment]
> 嘿，你设法解决了这个问题吗？

I didn't solve it

**Comment by Yuanyangkai** [comment]
> Hey @Yuanyangkai, have you managed to solve this issue?

This is the command I entered.
"mednextv1_plan_and_preprocess -t 521 -pl3d ExperimentPlanner3D_v21_customTargetSpacing_1x1x1"
This is my json file.
{
    "name": "Lung",
    "description": "artery and vein segmentation",
    "reference": "https://example.com/my_dataset",
    "licence": "CC BY-NC-SA 4.0",
    "tensorImageSize": "3d",
    "modality": {
        "0": "C"
    },
    "labels": {
        "0": "background",
        "1": "vein",
        "2": "artery"
    },

    "numTest": 3,
    "numTraining": 7,

    "test": [
        "E:/PythonProject/MedNeXt/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Task521_Lung/imagesTs/CTA_008.nii.gz",
        "E:/PythonProject/MedNeXt/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Task521_Lung/imagesTs/CTA_009.nii.gz",
        "E:/PythonProject/MedNeXt/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Task521_Lung/imagesTs/CTA_010.nii.gz"
    ],
    "training": [
        {
            "image": "E:/PythonProject/MedNeXt/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Task521_Lung/imagesTr/CTA_001.nii.gz",
            "label": "E:/PythonProject/MedNeXt/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Task521_Lung/labelsTr/CTA_001.nii.gz"
        },
        {
            "image": "E:/PythonProject/MedNeXt/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Task521_Lung/imagesTr/CTA_002.nii.gz",
            "label": "E:/PythonProject/MedNeXt/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Task521_Lung/labelsTr/CTA_002.nii.gz"
        },
        {
            "image": "E:/PythonProject/MedNeXt/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Task521_Lung/imagesTr/CTA_003.nii.gz",
            "label": "E:/PythonProject/MedNeXt/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Task521_Lung/labelsTr/CTA_003.nii.gz"
        },
        {
            "image": "E:/PythonProject/MedNeXt/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Task521_Lung/imagesTr/CTA_004.nii.gz",
            "label": "E:/PythonProject/MedNeXt/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Task521_Lung/labelsTr/CTA_004.nii.gz"
        },
        {
            "image": "E:/PythonProject/MedNeXt/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Task521_Lung/imagesTr/CTA_005.nii.gz",
            "label": "E:/PythonProject/MedNeXt/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Task521_Lung/labelsTr/CTA_005.nii.gz"
        },
        {
            "image": "E:/PythonProject/MedNeXt/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Task521_Lung/imagesTr/CTA_006.nii.gz",
            "label": "E:/PythonProject/MedNeXt/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Task521_Lung/labelsTr/CTA_006.nii.gz"
        },
        {
            "image": "E:/PythonProject/MedNeXt/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Task521_Lung/imagesTr/CTA_007.nii.gz",
            "label": "E:/PythonProject/MedNeXt/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Task521_Lung/labelsTr/CTA_007.nii.gz"
        }
    ]
}

**Comment by Yuanyangkai** [comment]
> Hey @Yuanyangkai, have you managed to solve this issue?

When I run my tests_mednext file, I also get an error.


D:\Anaconda3\envs\MeNeXt\python.exe "D:/Pycharm/PyCharm Community Edition 2024.1/plugins/python-ce/helpers/pycharm/_jb_pytest_runner.py" --target tests_mednext_miccai_architectures.py::Test_MedNeXt_archs 
Testing started at 下午7:30 ...
Launching pytest with arguments tests_mednext_miccai_architectures.py::Test_MedNeXt_archs --no-header --no-summary -q in E:\PythonProject\MedNeXt\mednext\tests

============================= test session starts =============================
collecting ... collected 8 items

tests_mednext_miccai_architectures.py::Test_MedNeXt_archs::test_init_and_forward[S-3] 
tests_mednext_miccai_architectures.py::Test_MedNeXt_archs::test_init_and_forward[B-3] 
tests_mednext_miccai_architectures.py::Test_MedNeXt_archs::test_init_and_forward[M-3] 
tests_mednext_miccai_architectures.py::Test_MedNeXt_archs::test_init_and_forward[L-3] 
tests_mednext_miccai_architectures.py::Test_MedNeXt_archs::test_init_and_forward[S-5] 
tests_mednext_miccai_architectures.py::Test_MedNeXt_archs::test_init_and_forward[B-5] 
tests_mednext_miccai_architectures.py::Test_MedNeXt_archs::test_init_and_forward[M-5] 
tests_mednext_miccai_architectures.py::Test_MedNeXt_archs::test_init_and_forward[L-5] 

============================== 8 failed in 8.25s ==============================
FAILED [ 12%]
tests\tests_mednext_miccai_architectures.py:6 (Test_MedNeXt_archs.test_init_and_forward[S-3])
torch.Size([4, 128, 128, 128]) != (1, 4, 128, 128, 128)

预期:(1, 4, 128, 128, 128)
实际:torch.Size([4, 128, 128, 128])
<点击以查看差异>

self = <tests_mednext_miccai_architectures.Test_MedNeXt_archs object at 0x0000020E4982E100>
model_size = 'S', kernel_size = 3

    @pytest.mark.parametrize("model_size, kernel_size", [
    ('S', 3),
    ('B', 3),
    ('M', 3),
    ('L', 3),
    ('S', 5),
    ('B', 5),
    ('M', 5),
    ('L', 5),
    ])
    def test_init_and_forward(self, model_size, kernel_size):
        m = create_mednext_v1(2, 4, model_size, kernel_size).cuda()
        input = torch.zeros((1,2,128,128,128), requires_grad=False).cuda()
        with torch.no_grad():
            output = m(input)
        del m
        inp_shape = input.shape
>       assert output[0].shape == (inp_shape[0], 4, *inp_shape[2:])
E       assert torch.Size([4, 128, 128, 128]) == (1, 4, 128, 128, 128)
E         
E         At index 0 diff: 4 != 1
E         Right contains one more item: 128
E         
E         Full diff:
E         + torch.Size([4, 128, 128, 128])
E         - (
E         -     1,
E         -     4,
E         -     128,
E         -     128,
E         -     128,
E         - )

tests_mednext_miccai_architectures.py:24: AssertionError
FAILED [ 25%]
tests\tests_mednext_miccai_architectures.py:6 (Test_MedNeXt_archs.test_init_and_forward[B-3])
torch.Size([4, 128, 128, 128]) != (1, 4, 128, 128, 128)

预期:(1, 4, 128, 128, 128)
实际:torch.Size([4, 128, 128, 128])
<点击以查看差异>

self = <tests_mednext_miccai_architectures.Test_MedNeXt_archs object at 0x0000020E53DFAA30>
model_size = 'B', kernel_size = 3

    @pytest.mark.parametrize("model_size, kernel_size", [
    ('S', 3),
    ('B', 3),
    ('M', 3),
    ('L', 3),
    ('S', 5),
    ('B', 5),
    ('M', 5),
    ('L', 5),
    ])
    def test_init_and_forward(self, model_size, kernel_size):
        m = create_mednext_v1(2, 4, model_size, kernel_size).cuda()
        input = torch.zeros((1,2,128,128,128), requires_grad=False).cuda()
        with torch.no_grad():
            output = m(input)
        del m
        inp_shape = input.shape
>       assert output[0].shape == (inp_shape[0], 4, *inp_shape[2:])
E       assert torch.Size([4, 128, 128, 128]) == (1, 4, 128, 128, 128)
E         
E         At index 0 diff: 4 != 1
E         Right contains one more item: 128
E         
E         Full diff:
E         + torch.Size([4, 128, 128, 128])
E         - (
E         -     1,
E         -     4,
E         -     128,
E         -     128,
E         -     128,
E         - )

tests_mednext_miccai_architectures.py:24: AssertionError
FAILED [ 37%]
tests\tests_mednext_miccai_architectures.py:6 (Test_MedNeXt_archs.test_init_and_forward[M-3])
torch.Size([4, 128, 128, 128]) != (1, 4, 128, 128, 128)

预期:(1, 4, 128, 128, 128)
实际:torch.Size([4, 128, 128, 128])
<点击以查看差异>

self = <tests_mednext_miccai_architectures.Test_MedNeXt_archs object at 0x0000020E53DFAF70>
model_size = 'M', kernel_size = 3

    @pytest.mark.parametrize("model_size, kernel_size", [
    ('S', 3),
    ('B', 3),
    ('M', 3),
    ('L', 3),
    ('S', 5),
    ('B', 5),
    ('M', 5),
    ('L', 5),
    ])
    def test_init_and_forward(self, model_size, kernel_size):
        m = create_mednext_v1(2, 4, model_size, kernel_size).cuda()
        input = torch.zeros((1,2,128,128,128), requires_grad=False).cuda()
        with torch.no_grad():
            output = m(input)
        del m
        inp_shape = input.shape
>       assert output[0].shape == (inp_shape[0], 4, *inp_shape[2:])
E       assert torch.Size([4, 128, 128, 128]) == (1, 4, 128, 128, 128)
E         
E         At index 0 diff: 4 != 1
E         Right contains one more item: 128
E         
E         Full diff:
E         + torch.Size([4, 128, 128, 128])
E         - (
E         -     1,
E         -     4,
E         -     128,
E         -     128,
E         -     128,
E         - )

tests_mednext_miccai_architectures.py:24: AssertionError
FAILED [ 50%]
tests\tests_mednext_miccai_architectures.py:6 (Test_MedNeXt_archs.test_init_and_forward[L-3])
torch.Size([4, 128, 128, 128]) != (1, 4, 128, 128, 128)

预期:(1, 4, 128, 128, 128)
实际:torch.Size([4, 128, 128, 128])
<点击以查看差异>

self = <tests_mednext_miccai_architectures.Test_MedNeXt_archs object at 0x0000020E53E1C070>
model_size = 'L', kernel_size = 3

    @pytest.mark.parametrize("model_size, kernel_size", [
    ('S', 3),
    ('B', 3),
    ('M', 3),
    ('L', 3),
    ('S', 5),
    ('B', 5),
    ('M', 5),
    ('L', 5),
    ])
    def test_init_and_forward(self, model_size, kernel_size):
        m = create_mednext_v1(2, 4, model_size, kernel_size).cuda()
        input = torch.zeros((1,2,128,128,128), requires_grad=False).cuda()
        with torch.no_grad():
            output = m(input)
        del m
        inp_shape = input.shape
>       assert output[0].shape == (inp_shape[0], 4, *inp_shape[2:])
E       assert torch.Size([4, 128, 128, 128]) == (1, 4, 128, 128, 128)
E         
E         At index 0 diff: 4 != 1
E         Right contains one more item: 128
E         
E         Full diff:
E         + torch.Size([4, 128, 128, 128])
E         - (
E         -     1,
E         -     4,
E         -     128,
E         -     128,
E         -     128,
E         - )

tests_mednext_miccai_architectures.py:24: AssertionError
FAILED [ 62%]
tests\tests_mednext_miccai_architectures.py:6 (Test_MedNeXt_archs.test_init_and_forward[S-5])
torch.Size([4, 128, 128, 128]) != (1, 4, 128, 128, 128)

预期:(1, 4, 128, 128, 128)
实际:torch.Size([4, 128, 128, 128])
<点击以查看差异>

self = <tests_mednext_miccai_architectures.Test_MedNeXt_archs object at 0x0000020E53E1C130>
model_size = 'S', kernel_size = 5

    @pytest.mark.parametrize("model_size, kernel_size", [
    ('S', 3),
    ('B', 3),
    ('M', 3),
    ('L', 3),
    ('S', 5),
    ('B', 5),
    ('M', 5),
    ('L', 5),
    ])
    def test_init_and_forward(self, model_size, kernel_size):
        m = create_mednext_v1(2, 4, model_size, kernel_size).cuda()
        input = torch.zeros((1,2,128,128,128), requires_grad=False).cuda()
        with torch.no_grad():
            output = m(input)
        del m
        inp_shape = input.shape
>       assert output[0].shape == (inp_shape[0], 4, *inp_shape[2:])
E       assert torch.Size([4, 128, 128, 128]) == (1, 4, 128, 128, 128)
E         
E         At index 0 diff: 4 != 1
E         Right contains one more item: 128
E         
E         Full diff:
E         + torch.Size([4, 128, 128, 128])
E         - (
E         -     1,
E         -     4,
E         -     128,
E         -     128,
E         -     128,
E         - )

tests_mednext_miccai_architectures.py:24: AssertionError
FAILED [ 75%]
tests\tests_mednext_miccai_architectures.py:6 (Test_MedNeXt_archs.test_init_and_forward[B-5])
torch.Size([4, 128, 128, 128]) != (1, 4, 128, 128, 128)

预期:(1, 4, 128, 128, 128)
实际:torch.Size([4, 128, 128, 128])
<点击以查看差异>

self = <tests_mednext_miccai_architectures.Test_MedNeXt_archs object at 0x0000020E53E1C1F0>
model_size = 'B', kernel_size = 5

    @pytest.mark.parametrize("model_size, kernel_size", [
    ('S', 3),
    ('B', 3),
    ('M', 3),
    ('L', 3),
    ('S', 5),
    ('B', 5),
    ('M', 5),
    ('L', 5),
    ])
    def test_init_and_forward(self, model_size, kernel_size):
        m = create_mednext_v1(2, 4, model_size, kernel_size).cuda()
        input = torch.zeros((1,2,128,128,128), requires_grad=False).cuda()
        with torch.no_grad():
            output = m(input)
        del m
        inp_shape = input.shape
>       assert output[0].shape == (inp_shape[0], 4, *inp_shape[2:])
E       assert torch.Size([4, 128, 128, 128]) == (1, 4, 128, 128, 128)
E         
E         At index 0 diff: 4 != 1
E         Right contains one more item: 128
E         
E         Full diff:
E         + torch.Size([4, 128, 128, 128])
E         - (
E         -     1,
E         -     4,
E         -     128,
E         -     128,
E         -     128,
E         - )

tests_mednext_miccai_architectures.py:24: AssertionError
FAILED [ 87%]
tests\tests_mednext_miccai_architectures.py:6 (Test_MedNeXt_archs.test_init_and_forward[M-5])
torch.Size([4, 128, 128, 128]) != (1, 4, 128, 128, 128)

预期:(1, 4, 128, 128, 128)
实际:torch.Size([4, 128, 128, 128])
<点击以查看差异>

self = <tests_mednext_miccai_architectures.Test_MedNeXt_archs object at 0x0000020E53E1C2B0>
model_size = 'M', kernel_size = 5

    @pytest.mark.parametrize("model_size, kernel_size", [
    ('S', 3),
    ('B', 3),
    ('M', 3),
    ('L', 3),
    ('S', 5),
    ('B', 5),
    ('M', 5),
    ('L', 5),
    ])
    def test_init_and_forward(self, model_size, kernel_size):
        m = create_mednext_v1(2, 4, model_size, kernel_size).cuda()
        input = torch.zeros((1,2,128,128,128), requires_grad=False).cuda()
        with torch.no_grad():
            output = m(input)
        del m
        inp_shape = input.shape
>       assert output[0].shape == (inp_shape[0], 4, *inp_shape[2:])
E       assert torch.Size([4, 128, 128, 128]) == (1, 4, 128, 128, 128)
E         
E         At index 0 diff: 4 != 1
E         Right contains one more item: 128
E         
E         Full diff:
E         + torch.Size([4, 128, 128, 128])
E         - (
E         -     1,
E         -     4,
E         -     128,
E         -     128,
E         -     128,
E         - )

tests_mednext_miccai_architectures.py:24: AssertionError
FAILED [100%]
tests\tests_mednext_miccai_architectures.py:6 (Test_MedNeXt_archs.test_init_and_forward[L-5])
torch.Size([4, 128, 128, 128]) != (1, 4, 128, 128, 128)

预期:(1, 4, 128, 128, 128)
实际:torch.Size([4, 128, 128, 128])
<点击以查看差异>

self = <tests_mednext_miccai_architectures.Test_MedNeXt_archs object at 0x0000020E53E1C370>
model_size = 'L', kernel_size = 5

    @pytest.mark.parametrize("model_size, kernel_size", [
    ('S', 3),
    ('B', 3),
    ('M', 3),
    ('L', 3),
    ('S', 5),
    ('B', 5),
    ('M', 5),
    ('L', 5),
    ])
    def test_init_and_forward(self, model_size, kernel_size):
        m = create_mednext_v1(2, 4, model_size, kernel_size).cuda()
        input = torch.zeros((1,2,128,128,128), requires_grad=False).cuda()
        with torch.no_grad():
            output = m(input)
        del m
        inp_shape = input.shape
>       assert output[0].shape == (inp_shape[0], 4, *inp_shape[2:])
E       assert torch.Size([4, 128, 128, 128]) == (1, 4, 128, 128, 128)
E         
E         At index 0 diff: 4 != 1
E         Right contains one more item: 128
E         
E         Full diff:
E         + torch.Size([4, 128, 128, 128])
E         - (
E         -     1,
E         -     4,
E         -     128,
E         -     128,
E         -     128,
E         - )

tests_mednext_miccai_architectures.py:24: AssertionError

进程已结束，退出代码为 1

**Comment by Yuanyangkai** [comment]
> Hey @Yuanyangkai, have you managed to solve this issue?



> Hey @Yuanyangkai, have you managed to solve this issue?

My data set .nii.gz file successfully ran in the nnunet_v2 official file, but after I modified the json file, it failed to run in the mednext file. I did not find the problem.

**Comment by Yuanyangkai** [comment]
> Hey @Yuanyangkai, have you managed to solve this issue?

My data set .nii.gz file successfully ran in the nnunet_v2 official file, but after I modified the json file, it failed to run in the mednext file. I did not find the problem.

**Comment by saikat-roy** [comment]
> line 289, in vstack return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting) ValueError: need at least one array to concatenate

So based on this, the nnunetv1 experiment planner cannot find any files to preprocess. I would start with making sure that the nnunetv1 code underneath can find the your files. The first thing I can see, which deviates from standard nnunetv1 recommendations are the paths in the dataset.json.

Could you try with relative paths instead of absolute paths in the `image` and `label`. Something like : `{"image":"./imagesTr/CTA_001.nii.gz","label":"./labelsTr/CTA_001.nii.gz"}`

**Comment by Yuanyangkai** [comment]
> > line 289, in vstack return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting) ValueError: need at least one array to concatenate
> 
> So based on this, the nnunetv1 experiment planner cannot find any files to preprocess. I would start with making sure that the nnunetv1 code underneath can find the your files. The first thing I can see, which deviates from standard nnunetv1 recommendations are the paths in the dataset.json.
> 
> Could you try with relative paths instead of absolute paths in the `image` and `label`. Something like : `{"image":"./imagesTr/CTA_001.nii.gz","label":"./labelsTr/CTA_001.nii.gz"}`

Still reporting an error.

(MeNeXt) PS E:\PythonProject\MedNeXt> mednextv1_plan_and_preprocess -t 521 -pl3d ExperimentPlanner3D_v21_customTargetSpacing_1x1x1
E:\PythonProject\MedNeXt\mednext\DATASET\nnUNet_raw_data_base\nnUNet_raw_data\Task521_Lung\imagesTr\CTA_003
E:\PythonProject\MedNeXt\mednext\DATASET\nnUNet_raw_data_base\nnUNet_raw_data\Task521_Lung\imagesTr\CTA_001
E:\PythonProject\MedNeXt\mednext\DATASET\nnUNet_raw_data_base\nnUNet_raw_data\Task521_Lung\imagesTr\CTA_004
E:\PythonProject\MedNeXt\mednext\DATASET\nnUNet_raw_data_base\nnUNet_raw_data\Task521_Lung\imagesTr\CTA_002
E:\PythonProject\MedNeXt\mednext\DATASET\nnUNet_raw_data_base\nnUNet_raw_data\Task521_Lung\imagesTr\CTA_006
E:\PythonProject\MedNeXt\mednext\DATASET\nnUNet_raw_data_base\nnUNet_raw_data\Task521_Lung\imagesTr\CTA_007
E:\PythonProject\MedNeXt\mednext\DATASET\nnUNet_raw_data_base\nnUNet_raw_data\Task521_Lung\imagesTr\CTA_005



 Task521_Lung
number of threads:  (8, 8)

qqq <nnunet_mednext.experiment_planning.alternative_experiment_planning.target_spacing.experiment_planner_v21_isotropic1mm.ExperimentPlanner3D_v21_customTargetSpacing_1x1x1 object at 0x00000184087D9340>
D:\Anaconda3\envs\MeNeXt\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
D:\Anaconda3\envs\MeNeXt\lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
not using nonzero mask for normalization
Are we using the nonzero mask for normalization? OrderedDict([(0, False)])
spacings: []
sizes: []
Traceback (most recent call last):
  File "\\?\D:\Anaconda3\envs\MeNeXt\Scripts\mednextv1_plan_and_preprocess-script.py", line 33, in <module>
    sys.exit(load_entry_point('mednextv1', 'console_scripts', 'mednextv1_plan_and_preprocess')())
  File "e:\pythonproject\mednext\mednext\nnunet_mednext\experiment_planning\nnUNet_plan_and_preprocess.py", line 162, in main
    exp_planner.plan_experiment()
  File "e:\pythonproject\mednext\mednext\nnunet_mednext\experiment_planning\experiment_planner_baseline_3DUNet.py", line 268, in plan_experiment
    median_shape = np.median(np.vstack(new_shapes), 0)
  File "D:\Anaconda3\envs\MeNeXt\lib\site-packages\numpy\core\shape_base.py", line 289, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
ValueError: need at least one array to concatenate
